# Generated by Django 3.1.4 on 2020-12-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_add', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ins_add', models.CharField(max_length=256, null=True)),
                ('inves_add', models.CharField(max_length=256, null=True)),
                ('supp_add', models.CharField(max_length=256, null=True)),
                ('area', models.CharField(choices=[('KIT', 'Kitchen'), ('HALL', 'Hall'), ('GAR', 'Garden'), ('BATH', 'Bathroom')], max_length=4, null=True)),
                ('type', models.CharField(choices=[('C', 'Critical'), ('NC', 'Non-Critical')], max_length=2)),
                ('home_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='sensor.home')),
            ],
        ),
    ]
