# Generated by Django 3.1.4 on 2020-12-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20201202_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpsp',
            name='type',
            field=models.CharField(choices=[('FIRE', 'Fire'), ('GAS', 'Gas Leakage'), ('BURG', 'Burglary')], max_length=200),
        ),
    ]
